version: "2"
services:
  web:
    container_name: rest-server
    restart: always
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo:4.2.2
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
